### ISSUE TITLE
Can I use this to bulk send ETH?

### ISSUE THREAD

**Issue by zulhfreelancer** [howeguo/Token-multisender#2]
Hi,

1. From my understanding, this tool is built to bulk send ERC20 tokens. Can I this to bulk send ETH too? For example, I can use this tool to send 0.00001ETH/address to 1,000 addresses?

2. What is the contract address of this project in mainnet? Just want to look at it before performing any transactions.

3. What is the maximum number of recipients I can put for each drop? 1,000 addresses? 10,000 addresses? No limit?

Thanks.

**Comment by howeguo** [comment]
Sorry for late reply
1) sure, valid for distribution ETH
2) Here is the source code https://etherscan.io/address/0x2f6321db2461f68676f42f396330a4dc4a8f49df#code
3) Default 175, max 200 for a single tx, that’s the limit of Etherum block, But u can upload the whole file include all your addresses, the DAPP will split it into sereval txs automatically, no limit

U can find more info by our website https://bulksender.app

**Comment by zulhfreelancer** [comment]
Thank you for your reply.

**Comment by howeguo** [comment]
> Thank you for your reply.
U can find more history for distribution ETH from here 

https://etherscan.io/tx/0xddd18bc544dfebcd81692066b429a96347a991ce22fcd4eb2354fda123fdefe9
https://etherscan.io/txs?a=0x2f6321db2461f68676f42f396330a4dc4a8f49df&p=8

**Comment by rstormsf** [comment]
Try https://multisender.app, it's much better
