### ISSUE TITLE
Learned upgradability of contracts and lost your tx history? 

### ISSUE THREAD

**Issue by rstormsf** [howeguo/Token-multisender#4]
good job!

**Comment by howeguo** [comment]
> good job!
Thanks!
Its hard for me to make this decision, cause as you said, we lost our 7k txs, but we need to learn more something new.
FYI,  you and your team did so great for your lastest version.
I respect you！

**Comment by rstormsf** [comment]
@howeguo I want to ask you a few questions: find me on telegram, seems like I'm banned in your telegram group. 
Even though I really don't like what you are doing, and you are stealing my users from my telegram group by private messaging them, there is something we can talk about

**Comment by howeguo** [comment]
> @howeguo I want to ask you a few questions: find me on telegram, seems like I'm banned in your telegram group.
> Even though I really don't like what you are doing, and you are stealing my users from my telegram group by private messaging them, there is something we can talk about

Hey rstormsf ,
I was banned in your telegram group long time ago, and I heard you are stealing my user from my group, so I banned u.
If there are some misunderstanding, I am sorry about that.

Your product is great, you dont worry about it, just be confident, man

**Comment by rstormsf** [comment]
@howeguo 
yes, because I learned how you were stealing my users, not cool, man. Not cool

**Comment by howeguo** [comment]
> @howeguo
> yes, because I learned how you were stealing my users, not cool, man. Not cool

@rstormsf rstormsf, so you are stealing my user, right? and copy my VIP function, and send your token(Taken your host) to our dApp user, this is what you are doing, not cool, man. Not cool

**Comment by rstormsf** [comment]
actually, why don't you raise your fee, so you can make more money? @howeguo 
There is no benefit for you to charge low
