### ISSUE TITLE
error:-32000 | gas required exceeds allowance (600000) or always failing transaction

### ISSUE THREAD

**Issue by lhalcyon** [howeguo/Token-multisender#5]
我这边在rinkeby网络上部署了合约,然后也approve成功了.但是调用的时候始终报这个错.   括号里的数字是我这边传递的gasLimit

**Comment by howeguo** [comment]
> 我这边在rinkeby网络上部署了合约,然后也approve成功了.但是调用的时候始终报这个错. 括号里的数字是我这边传递的gasLimit

你可以把合约的手续费设置为0应该就好了

**Comment by lhalcyon** [comment]
> > 我这边在rinkeby网络上部署了合约,然后也approve成功了.但是调用的时候始终报这个错. 括号里的数字是我这边传递的gasLimit
> 
> 你可以把合约的手续费设置为0应该就好了

你好, 我这边设置手续费为0后解决了. 但是在执行multisendToken时,我设置转给两个地址不通的金额token, 结果只有后面设置的地址收到了token  具体[tx hash](https://rinkeby.etherscan.io/tx/0xa4c2c09ca39e446d4ddcd00e37d1154db5985b609e63d94d4a02981849236c91)
